/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


#ifndef _Included_polylink_sdk_pl_c_nativ_PolyLinkAPI21
#define _Included_polylink_sdk_pl_c_nativ_PolyLinkAPI21
#ifdef __cplusplus

#include "native-lib.h"
extern "C" {
#endif

JNIEXPORT void JNICALL Java_polylink_sdk_pl_c_nativ_PolyLinkAPI21_dos
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
