/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marswin89_marsdaemon_nativ_NativeDaemonAPI20 */

#ifndef _Included_PolyLink_SDK_API20
#define _Included_PolyLink_SDK_API20
#ifdef __cplusplus
#include "../native-lib.h"
extern "C" {
#endif

JNIEXPORT void JNICALL Java_polylink_sdk_pl_c_nativ_PolyLinkAPI20_dos
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
